
NUMBER_OF_EXPERIMENTS_PER_ALGORITHM: 100

NUMBER_OF_ITERATIONS_PER_EXPERIMENT: 10000

SEED: 42

A:  
  - Dist: Normal
    Params: [0.4, 0.5]
  
  - Dist: Normal
    Params: [0.5, 0.3]

  - Dist: Normal
    Params: [0.5, 0.5]

  - Dist: Normal
    Params: [0.5, 0.7]

ξ:
  - Dist: Categorical
    Params: 4

PlotSeriesOverTime:
  - MABField: regret_fixed
    FileName: "ExperimentOutputs/plot_of_regret_fixed_over_time"
    DisplayPlot: false

  - MABField: regret_pseudo
    FileName: "ExperimentOutputs/plot_of_regret_pseudo_over_time"
    DisplayPlot: false

  - MABField: γ  
    FileName: "ExperimentOutputs/plot_of_action_over_time"
    DisplayPlot: false

PlotSeriesHistogram:
  - MABField: γ  
    FileName: "ExperimentOutputs/plot_of_action_histogram"
    DisplayPlot: false

Algorithms: ["ExponentiatedGradient", "FtrlExponentiatedGradient", "EXP3", "ExploreThenCommit", "UpperConfidenceBound", "EpsilonGreedy", "LinearDecayedEpsilonGreedy", "ExpDecayedEpsilonGreedy", "Hedge"]

ExponentiatedGradientDefaultValues:
  - η: 0.01

FtrlExponentiatedGradientDefaultValues:
  - α: 0.8493218002880191 #α=1/sqrt(log(length(A)))

EXP3DefaultValues:
  - η: 0.01 #η=1/sqrt(NUMBER_OF_ITERATIONS_PER_EXPERIMENT)

ExploreThenCommitDefaultValues:
  - m: 10

UpperConfidenceBoundDefaultValues:
  - α: 3

EpsilonGreedyDefaultValues:
  - ϵ: 0.1

LinearDecayedEpsilonGreedyDefaultValues:
  - ϵ_start: 1.0
  - ϵ_end: 0.0

ExpDecayedEpsilonGreedyDefaultValues:
  - ϵ_start: 1.0
  - ϵ_end: 0.001

HedgeDefaultValues:
  - η: 0.1
