
NUMBER_OF_EXPERIMENTS_PER_ALGORITHM: 100

NUMBER_OF_ITERATIONS_PER_EXPERIMENT: 10

SEED: 42

A:  
  - Dist: Beta
    Params: [0.15, 0.7]
  
  - Dist: Beta
    Params: [0.54,0.2]

  - Dist: Beta
    Params: [0.38, 0.5]

ξ:
  - Dist: Categorical
    Params: [0.3333333333333333, 0.3333333333333333, 0.3333333333333333]

PlotSeriesOverTime:
  - MABField: regret_fixed
    FileName: "ExperimentOutputs/plot_of_regret_over_time"

  - MABField: γ  
    FileName: "ExperimentOutputs/plot_of_action_over_time"

PlotSeriesHistogram:
  - MABField: γ  
    FileName: "ExperimentOutputs/plot_of_action_histogram"
