
NUMBER_OF_EXPERIMENTS_PER_ALGORITHM: 100

NUMBER_OF_ITERATIONS_PER_EXPERIMENT: 10000

SEED: 42

A:  
  - Dist: Normal
    Params: [0.4, 0.5]
  
  - Dist: Normal
    Params: [0.5, 0.3]

  - Dist: Normal
    Params: [0.5, 0.5]

  - Dist: Normal
    Params: [0.5, 0.7]

ξ:
  - Dist: Categorical
    Params: 4

PlotSeriesOverTime:
  - MABField: regret_fixed
    FileName: "ExperimentOutputs/plot_of_regret_over_time"

  - MABField: γ  
    FileName: "ExperimentOutputs/plot_of_action_over_time"

PlotSeriesHistogram:
  - MABField: γ  
    FileName: "ExperimentOutputs/plot_of_action_histogram"
